### ISSUE TITLE
Remove [ ]

### ISSUE THREAD

**Issue by marwie** [Unity-Technologies/com.unity.editoriterationprofiler#1]
Hello,

is there a reason for the brackets surrounding every line? I think it decreases readability quite a bit

![image](https://user-images.githubusercontent.com/5083203/94150523-88552200-fe79-11ea-9921-1c05c790a5b0.png)

**Comment by Rares95** [comment]
Right, I will look into removing them for non-leaf nodes :D

**Comment by marwie** [comment]
Why not remove them for leaf nodes as well?

**Comment by Rares95** [comment]
I suppose it doesn't really make much sense, sure I will do that then

**Comment by midopooler** [comment]
@Rares95 Should I work on this issue or are you already doing it?

**Comment by Rares95** [comment]
https://github.com/Unity-Technologies/com.unity.editoriterationprofiler/commit/e05c43da15a508a88c82f9606ef49c934a988090

**Comment by midopooler** [comment]
Sorry I didn't notice this. The issue was open, hence I showed my interest. :p

**Comment by Rares95** [comment]
Oh yeah I just did it, was a quick fix :P
